version: '3'
services:
  mongodb:
    image: "mongo:latest"
    restart: unless-stopped
    command: --nojournal --maxConns 1000
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none
  histomicsui:
    environment:
      - GIRDER_MONGO_URI=mongodb://mongodb:27017/girder
    command: ["gunicorn", "histomicsui.wsgi:app", "--bind=0.0.0.0:8080", "--workers=1"]
    ports:
      - "8080:8080"
    volumes:
      - ./assetstore:${PWD}/assetstore
    build:
      context: .
      dockerfile: ./histomicsui.Dockerfile
