version: '3'
services:
  mongodb:
    image: "mongo:latest"
    restart: unless-stopped
    command: --nojournal --maxConns 1000
    volumes:
      - ./db:/data/db
    network_mode: host
    logging:
      driver: none
  histomicsui:
    network_mode: host
    volumes:
      - ./assetstore:${PWD}/assetstore
    build:
      context: .
      dockerfile: ./histomicsui.Dockerfile
